version: '3'

services:
  web:
    image: dtr.robert.dtcntr.net/engineering/countdown-nginx
    deploy:
            labels:
                com.docker.ucp.mesh.http.8080: "external_route=http://countdown.cluster.robert.dtcntr.net,internal_port=8080"
    ports:
      - "8080:80"
    networks:
      - ucp-hrm


networks:
    ucp-hrm:
        external: true
